apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audit-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/robpearson/AuditService
    targetRevision: HEAD
    path: charts/audit-service
    helm:
      releaseName: audit-service
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: audit-service-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
